branches:
  only: 
    - next
matrix:
  include:
    - stage: "Build next"
      os: linux
      language: android
      env:
        - TestVersion="next"
      jdk: oraclejdk8
      before_install:
        - nvm install 8.9.4
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - tns platform add android@next
        - cd ../seed-tests && npm i
      script: travis_wait travis_retry npm run test.android
      dist: precise
    - os: osx
      env:
        - TestVersion="next"
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      osx_image: xcode9.3
      before_script:
        - tns platform add ios@next
        - cd ../seed-tests && npm i
      script: travis_wait travis_retry npm run test.ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-23
    - android-26
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd src
    - npm uninstall tns-core-modules -D && npm install tns-core-modules@next -D
    - cd ../demo
    - npm uninstall tns-core-modules -P && npm install tns-core-modules@next -P
    - npm uninstall nativescript-dev-webpack -D && npm install nativescript-dev-webpack@next -D
    